//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookdbEntities : DbContext
    {
        public bookdbEntities()
            : base("name=bookdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customerserials> customerserials { get; set; }
        public virtual DbSet<error> error { get; set; }
        public virtual DbSet<office> office { get; set; }
        public virtual DbSet<setting> setting { get; set; }
        public virtual DbSet<setValues> setValues { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<userSetValues> userSetValues { get; set; }
        public virtual DbSet<customers> customers { get; set; }
    }
}
