//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerserials
    {
        public int customerSerialId { get; set; }
        public string serial { get; set; }
        public string officeName { get; set; }
        public string Number { get; set; }
        public string customerHardCode { get; set; }
        public string activateCode { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public int yearCount { get; set; }
        public Nullable<System.DateTime> bookDate { get; set; }
        public string confirmStat { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> createUserId { get; set; }
        public Nullable<int> updateUserId { get; set; }
        public Nullable<int> isActive { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> activatedate { get; set; }
        public bool isProgramActivated { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
